### PR TITLE
Fixes #2 Feedback / after-the-fact-review of XPathTransformer :)

### LINKED ISSUE #2: Feedback / after-the-fact-review of XPathTransformer :)
Sorry this is coming too late, but I just gave a look at the XPath transformer and had some pointers to give :-)

 * The initialize method should actually throw an exception to prevent that the job even begins. If the configuration is invalid then there's no point in running the job IMO. I would not recommend using the publishMessage mechanism for this since it's a bit too "passive" for my taste.
 * Similarly you might add a ```@Validate``` annotated method which would throw exceptions early on to give the user an idea already while building his job that it is incorrectly configured.
 * Not important, but we have an XmlUtils class which you might leverage to create the document builder with a few less lines of code :) Same with the Transformer (although settings might not be exactly the same - I would recommend you look at it first).

### PR DESCRIPTION
**Pull request by arjansh**
- Refactored the initialize method so it throws an Exception in case an XPath expression can't be compiled.
- I don't see what I could validate in a `@Validate` annotated method, because the only thing that could cause problems which would cause a job to run with invalid configuration are the configured XPath expressions, which already cause the initialize method to throw an Exception now. Maybe I'm missing something here however.
- The XmlUtils class is not available in DataCleaner 4.5.3 which this extension depends on, therefore I didn't use it.

### CODE REVIEW

**Comment by kaspersorensen** [comment]
The validate method is invoked at a different time than the Initialize method - that's the main difference. The Initialize method is called only when a job is actually starting. The validate method is called many times during job building to ensure that the configuration is correct. So I think a very similar method for validation would still make sense. Obviously a validation method should then not change state of the object (the compiled patterns don't need to be saved anywhere) but other than that probably they're identical.

No problem with not using the XmlUtils class :)

File: src/main/java/org/datacleaner/extension/xml/XPathTransformer.java [hunk 1]
```diff
@@ -57,7 +57,7 @@
     private TransformerFactory transformerFactory;
 
     @Initialize
-    public void init() {
+    public void init() throws IllegalArgumentException {
```
Comment (LosD) [inline src/main/java/org/datacleaner/extension/xml/XPathTransformer.java]: It's not super good practice to add runtime exception to throws, as it hides what the a user of the class actually needs to explicitly catch.

If you want to document it,  better add it in JavaDoc using @throws

File: src/test/java/org/datacleaner/extension/xml/XPathTransformerTest.java [hunk 2]
```diff
@@ -11,9 +11,14 @@
 import org.datacleaner.data.MockInputRow;
 import org.easymock.EasyMock;
 import org.junit.Before;
+import org.junit.Rule;
 import org.junit.Test;
+import org.junit.rules.ExpectedException;
 
 public class XPathTransformerTest {
+    @Rule
+    public final ExpectedException expectedException = ExpectedException.none();
```
Comment (LosD) [inline src/test/java/org/datacleaner/extension/xml/XPathTransformerTest.java]: Rules! Beautiful! :)

(Getting @kaspersorensen to use these has been an uphill battle. :))
